# Generated by Django 3.2.3 on 2021-05-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMgmtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_text', models.CharField(max_length=200)),
                ('case_result', models.CharField(max_length=20)),
                ('case_log', models.CharField(max_length=500)),
                ('case_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
